### PR TITLE
Remove deepcopy used in call alicloud API

### PR DESCRIPTION
**Pull request by kevin-lacoo**
**What this PR does / why we need it**:
The `deepcopy` call is not running correctly in some environment, this PR replace `deepcopy` call by adding a `__clean_request` function .
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
NONE
```

### CODE REVIEW

**Comment by kevin-lacoo** [comment]
Hi @vlerenc , I replaced the `deepcopy` call with a new `__clean_request` function.

**Review by vlerenc — APPROVED** [review]

**Comment by vlerenc** [comment]
@kevin-lacoo Have you tested it (functionally and against the different Python versions)? Shall I release a new version?

**Comment by kevin-lacoo** [comment]
> @kevin-lacoo Have you tested it (functionally and against the different Python versions)? Shall I release a new version?

I tested it in 3.9 and 3.10.

**Comment by vlerenc** [comment]
Great, thank you. I now tested it also with 3.11 and now it works out of the box. I will then make a new release. Thanks for your work and support @kevin-lacoo !

**Pull request merged**
