### PR TITLE
Remove unused vsphere helper functions

### PR DESCRIPTION
**Pull request by MartinWeindel**
**What this PR does / why we need it**:
Remove unused vsphere helper functions

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other developer
Remove unused vsphere helper functions
```

### CODE REVIEW

**Comment by vlerenc** [comment]
/lgtm Thank you @MartinWeindel 

@msohn Can we leave it like this? `chaosgarden/vsphere/pchelper.py` would be "based on the sample code" in https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/tools/pchelper.py, which is under Apache license, but also "amended with additional functions". I diffed the files. Martin's new file contains all of the original source plus some additional functions. Are we OK/clean with this approach?

**Comment by msohn** [comment]
You can copy code from pyvmomi-community-samples under the Apache-2 license but you need to fulfil its license terms, see https://github.com/vmware/pyvmomi-community-samples/blob/master/LICENSE#L89

- 4a. is fulfilled since you redistribute under Apache-2 license
- Note that you still need to fulfil 4b, 4c and 4d for the copied code

**Comment by vlerenc** [comment]
Thank you @msohn once again!

@MartinWeindel I saw you pushed an update making 4b.) even clearer.

I'll then merge the PR now.

**Review by vlerenc — APPROVED** [review]
/lgtm

**Comment by vlerenc** [comment]
Post-merge, I noticed I must delete the BSD license to make the `reuse` linter happy. I also changed the copyright to "Copyright (c) 2014-2021 VMware, Inc. All Rights Reserved." @MartinWeindel as the original file had none and the `__init__.py` had this one. I guess, that's OK?

**Pull request merged**
